version: "3"
services:
  logging:
    image: jasonmichels/logging:develop
    logging:
      driver: "fluentd"
    depends_on:
      - fluentd
  secondlogging:
    image: jasonmichels/secondlogging:develop
    logging:
      driver: "fluentd"
    depends_on:
      - fluentd
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=testing
  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
    volumes:
      - /Users/michelsja/Sites/data/influxdb:/var/lib/influxdb
      - /Users/michelsja/Sites/data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
  fluentd:
    build: ./fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - influxdb
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS="DockerLogs:1:3"
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock